senzing-garage/go-logging

- Makefile
- main.go
- messageformat/main.go
- messageformat/messageformat_json.go
- messageformat/messageformat_terse.go
- messageformat/messageformat_test.go
- messageid/main.go
- messageid/messageid_default.go
- messageid/messageid_test.go
- messagelogger/main.go
- messagelogger/messagelogger_impl.go
- messageloglevel/main.go
- messageloglevel/messagelevel_info.go
- messageloglevel/messagelevel_null.go
- messageloglevel/messagelevel_senzingapi.go
- messageloglevel/messagelevel_test.go
- messagestatus/messagestatus_null.go
- messagestatus/messagestatus_senzingapi.go
- messagestatus/messagestatus_test.go
- messagetext/main.go
- messagetext/messagetext_default.go
- messagetext/messagetext_test.go
> Issue 3.dockter.4

- messagelogger/main.go
- messagelogger/messagelogger_impl.go
> #3 Savepoint

- Makefile
- doc.go
- logger/logger_default.go
- main.go
- messageformat/main.go
- messageformat/messageformat_default.go
- messageformat/messageformat_json.go
- messageformat/messageformat_test.go
- messageid/main.go
- messageid/messageid_templated.go
- messageid/messageid_test.go
- messagelogger/main.go
- messagelogger/messagelogger_default.go
- messagelogger/messagelogger_test.go
- messageloglevel/main.go
- messageloglevel/messageloglevel_by_id_range.go
- messageloglevel/messageloglevel_default.go
- messageloglevel/messageloglevel_senzingapi.go
- messageloglevel/messageloglevel_static.go
- messagestatus/messagestatus_by_id.go
- messagestatus/messagestatus_by_id_range.go
- messagestatus/messagestatus_senzingapi.go
- messagetext/main.go
- messagetext/messagetext_null.go
- messagetext/messagetext_templated.go
- messagetext/messagetext_test.go
> Issue 3.dockter.9

- Makefile
- doc.go
- logger/logger_default.go
- logger/main.go
- main.go
- messageformat/main.go
- messageformat/messageformat_default.go
- messageformat/messageformat_json.go
- messageid/main.go
- messageid/messageid_default.go
- messageid/messageid_templated.go
- messagelogger/main.go
- messagelogger/messagelogger_default.go
- messageloglevel/main.go
- messageloglevel/messageloglevel_by_id_range.go
- messageloglevel/messageloglevel_default.go
- messageloglevel/messageloglevel_senzingapi.go
- messageloglevel/messageloglevel_static.go
- messagestatus/main.go
- messagestatus/messagestatus_by_id.go
- messagestatus/messagestatus_by_id_range.go
- messagestatus/messagestatus_null.go
- messagestatus/messagestatus_senzingapi.go
- messagetext/main.go
- messagetext/messagetext_null.go
- messagetext/messagetext_templated.go
> Issue 3.dockter.10

- CHANGELOG.md
- README.md
- doc.go
- messagelogger/main.go
- messagelogger/messagelogger_default.go
- messagelogger/messagelogger_test.go
- messageloglevel/messageloglevel_by_id_range.go
- messageloglevel/messageloglevel_senzingapi.go
> Issue 3.dockter.11

- README.md
- doc.go
- main.go
- main_test.go
- messagestatus/messagestatus_by_id.go
- messagestatus/messagestatus_senzingapi.go
- messagestatus/messagestatus_test.go
> Issue 3.dockter.12

- CHANGELOG.md
- messagestatus/messagestatus_senzingapi.go
> Issue 3.dockter.16

- CHANGELOG.md
- Makefile
- doc.go
- logger/logger_default.go
- logger/logger_test.go
- logger/main.go
- main.go
- main_test.go
- messageformat/main.go
- messageformat/messageformat_default.go
- messageformat/messageformat_json.go
- messageformat/messageformat_senzing.go
- messageformat/messageformat_test.go
- messageid/messageid_senzing.go
- messageid/messageid_test.go
- messagelogger/main.go
- messagelogger/messagelogger_test.go
- messageloglevel/messageloglevel_by_id_range.go
- messageloglevel/messageloglevel_senzing.go
- messageloglevel/messageloglevel_senzingapi.go
- messageloglevel/messageloglevel_test.go
- messagestatus/messagestatus_senzing.go
- messagestatus/messagestatus_test.go
- messagetext/messagetext_senzing.go
- messagetext/messagetext_test.go
> Issue 20.dockter.1

- Makefile
- main.go
- messagelogger/main.go
> #26 Savepoint

- doc.go
- main.go
- messagelevel/main.go
- messagelevel/messagelevel_by_id_range.go
- messagelevel/messagelevel_default.go
- messagelevel/messagelevel_senzing.go
- messagelevel/messagelevel_senzingapi.go
- messagelevel/messagelevel_test.go
- messagelogger/main.go
> #35 Added messagelevel variables

- messagelevel/messagelevel_by_id_range.go
- messagelevel/messagelevel_default.go
- messagelevel/messagelevel_senzing.go
- messagelevel/messagelevel_senzingapi.go
- messagelevel/messagelevel_test.go
- messagestatus/main.go
- messagestatus/messagestatus_senzingapi.go
- messagestatus/messagestatus_test.go
> #33 Savepoint

- messagelocation/messagelocation_test.go
> #30 Improve tests for CallerSkip

- CHANGELOG.md
> #30 Prepare for versioned release

- CHANGELOG.md
- messagelogger/main.go
> #41 added messagelogger.Level

- CHANGELOG.md
- messageformat/messageformat_json.go
- messageformat/messageformat_senzing.go
- messagelogger/main.go
- messagestatus/messagestatus_senzing.go
- messagestatus/messagestatus_senzingapi.go
> #41 Fix ineffective assignments

- .github/workflows/go-proxy-pull.yaml
- Makefile
> #46 Update GO_PACKAGE_NAME

- Makefile
- README.md
> #54 Fix documentation

- CHANGELOG.md
- go.mod
- go.sum
- logging/main.go
> Issue 58.dockter.1

- .github/workflows/go-test.yaml
- CHANGELOG.md
- go.mod
- go.sum
- logging/main.go
> Issue 61.dockter.1

- .github/workflows/add-dependabot-request-to-project-t-comm.yaml
- .github/workflows/add-issue-to-project-t-comm.yaml
- CHANGELOG.md
- go.mod
- go.sum
> Issue 58.dockter.2

- CHANGELOG.md
- README.md
- logging/logging.go
- main.go
> Issue 27.dockter.1

- CHANGELOG.md
- README.md
- logging/logging.go
- logging/main.go
- main.go
> #67 Prepare for versioned release

- .github/workflows/add-dependabot-request-to-project-t-comm.yaml
- .github/workflows/add-issue-to-project-t-comm.yaml
- .github/workflows/add-triage-label.yaml
- .github/workflows/go-test-darwin.yaml
- .github/workflows/go-test-linux.yaml
- .github/workflows/go-test-windows.yaml
- .github/workflows/gosec.yaml
- .github/workflows/identify-customer.yaml
- .gitignore
- CHANGELOG.md
- Makefile
- Makefile.darwin
- Makefile.linux
- Makefile.windows
- go.mod
- go.sum
> #83 Refactor to template

- CHANGELOG.md
- go.mod
- go.sum
> 58.dockter.4

- CHANGELOG.md
- go.mod
- go.sum
> 109 dockter 2
